appname = test_api_crud
httpport = ${GESTION_PERSONAS_CRUD_HTTP_PORT}
runmode = ${GESTION_PERSONAS_CRUD_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

# cadena de conexion fragmentado
PGuser = ${GESTION_PERSONAS_CRUD_PGUSER}
PGpass = ${GESTION_PERSONAS_CRUD_PGPASS}
PGhost = ${GESTION_PERSONAS_CRUD_PGHOST}
PGport = ${GESTION_PERSONAS_CRUD_PGPORT}
PGdb   = ${GESTION_PERSONAS_CRUD_PGDB}
PGschema = ${GESTION_PERSONAS_CRUD_PGSCHEMA}
